#!/bin/bash

if [[ -z $1 ]];then
	echo "You need to provide a command to show manual or --help for options"
	exit
fi
title=$1
if [[ -z $2 ]]; then 
echo "Trying at die.net"
dt=$(links -dump https://linux.die.net/man/1/$1)
tit="/die.net"
fi

if [[ $dt == *"Not Found"* || $2 == "--mankier" ]]; then
	echo "die.net skipped. Trying mankier.com"
	dt=$(links -dump  https://www.mankier.com/1/$1)
	tit="/mankier"
fi

if [[ $dt == *"Not Found"* || $2 == "--manhenet" ]]; then
	echo "die.net and mankier.com skpped . Trying man.he.net"
	dt=$(links -dump  "http://man.he.net/?topic=$1&section=all")
	tit="/man.he.net"
fi

if [[ $dt == *"No matches"* ]]; then
	echo "No man Found"
	exit
fi

yad --text-info<<<"$dt" --height=500 --width=800 --center --title="$title$tit Manual " --wrap --show-uri --no-markup &	
